name: OneWayElytra
version: '1.0.4'
main: de.philippstamp.oneWayElytra.OneWayElytra
author: JuggleGaming
api-version: '1.21.11'

commands:
  onewayelytra:
    description: "OneWayElytra"
    aliases: [owe]