name: OneWayElytra
version: '1.0.3'
main: de.philippstamp.oneWayElytra.OneWayElytra
author: JuggleGaming
api-version: '1.21.4'
softdepend:
  - WorldGuard

commands:
  onewayelytra:
    description: "OneWayElytra"
    aliases: [owe]