name: OneWayElytra
version: '1.1.2'
main: de.jugglegaming.oneWayElytra.OneWayElytra
author: JuggleGaming
api-version: '1.21.11'

commands:
  onewayelytra:
    description: "OneWayElytra"
    aliases: [owe]