name: OneWayElytra
version: '1.0.0'
main: de.philippstamp.oneWayElytra.OneWayElytra
author: JuggleGaming
api-version: '1.21.3'

commands:
  onewayelytra:
    description: "OneWayElytra"
    aliases: [owe]