name: OneWayElytra
version: '1.0.2'
main: de.philippstamp.oneWayElytra.OneWayElytra
author: JuggleGaming
api-version: '1.21.4'

commands:
  onewayelytra:
    description: "OneWayElytra"
    aliases: [owe]